### ISSUE TITLE
Causing Crash with MC launcher

### ISSUE THREAD

**Issue by Areolata7** [canitzp/FeederHelmet#12]
Tried to add FeederHelmet-1.6.1 and it causes immediate crash in the MC launcher. I don't even get as far as trying to load my world. I am running 1.14.4 but the last mod file was released in July and I am running Forge 28.1.26 which is much newer. 

I think I found the three crash reports. Crashed during initial launch and all show FeederHelmet-1.6.1 Error

[crash-2019-10-12_10.02.20-client.txt](https://github.com/canitzp/FeederHelmet/files/3725775/crash-2019-10-12_10.02.20-client.txt)
[crash-2019-10-12_10.05.14-client.txt](https://github.com/canitzp/FeederHelmet/files/3725776/crash-2019-10-12_10.05.14-client.txt)
[crash-2019-10-12_10.08.30-client.txt](https://github.com/canitzp/FeederHelmet/files/3725777/crash-2019-10-12_10.08.30-client.txt)

**Comment by canitzp** [comment]
You're right when you say that they state that AutoFeederHelmet shows ERROR and I don't know why, but the actual crashes come from xercamod (first report) and from AnimalNet (second and third crash)

**Comment by Areolata7** [comment]
Okay But I am still running Xerca and have not had any issues with it or any of the other mods I have been running. So maybe a conflict specifically between Xerca and AutoFeederHelmet?

**Comment by Areolata7** [comment]
Sorry I just saw your mention of AnimalNet also. I have been running that mod for months without issue and Xerca I started later but I still run both right now.

**Comment by canitzp** [comment]
I can try to reproduce your setup and maybe find the error

**Comment by canitzp** [comment]
Many many thanks to you for posting this bug. It is actually due to a internal change from forge back on the 5th of August (1.14.4-28.0.45) and it is a bug by AutoFeederHelmet. I'll test a new version and upload it as soon as I can.
As a side question, how have you found my mod and why do you want to add it to your modpack? I'm just curious. Also after you played with it, maybe you can comment on curseforge if you like the mod or if you want features or other improvements.

**Comment by canitzp** [comment]
What I have to add here is that, the other mods also crash due to internal forge changes, so you want to inform their authors too (with crash report)
