### ISSUE TITLE
NBT data scrubbed clean

### ISSUE THREAD

**Issue by Dalethium** [canitzp/FeederHelmet#2]
When adding a auto feeder to a helmet from the spectrite mod, all the enchants etc get totally deleted. 

Also, on that note I was editing the nbt of the helm to add the effect manually without losing it, and the "auto feeder attached" thing in yellow pops up even if the ``AutoFeederHelmet`` tag is set to 0.

PS: I love the mod! Keep up the good work!

**Comment by canitzp** [comment]
We'll take a look into the spectrite helmet problem, but spontanious i can't tell whats happening.
It doesn't matter if the AutoFeederHelmet tag is 0 or 1, I just ask if there is any and since therr is no removal from this mod, you technically aren't able to remive it at all, except deleting the tag via nbt
