### ISSUE TITLE
Suggestion:  'default' setting for "food_blacklist" option

### ISSUE THREAD

**Issue by markygnlg** [canitzp/FeederHelmet#22]
(Note: I can't find the "Suggestion" tag)

I've seen some questions about disabling rotten_flesh & I had the same question too but it was answered in the curseforge posts.

This led me to add more items to the "food_blacklist" option - but because I used the semi-colon instead of the comma, my game kept crashing, which made me think that maybe if there were at least 2 items in the "food_blacklist" option as defaults then people could quickly see the format of the string & could then easily add their own choices. The list I made was based on food I wanted to cook before eating (both for food & saturation levels - thanks to the "AppleSkin" mod for teaching the difference) but also for items I wanted to replant.

I eventually used the line:

food_blacklist = ["minecraft:rotten_flesh", "minecraft:porkchop", "minecraft:beef", "minecraft:mutton", "minecraft:salmon", "minecraft:chicken", "minecraft:rabbit", "minecraft:potato"]

I did not add cod, carrots, tropical fish, spider eye, etc. since I find those items useless in my play-throughs - & they add to the "A Balanced Diet" Advancement.

**Comment by canitzp** [comment]
I thought about some default blacklisted foods before. I probably use rotten flesh and spider eyes, sine nobody wants to eat it anyways

**Comment by markygnlg** [comment]
I added some suggestions in the curseforge forum. The post will eventually be pushed down so maybe you could read it & add some of the info into your curseforge description - ie. I didn;t know why my 60 durability helmet was so low since I'm using an OP armour mod ("[Redstone-Tools](https://www.curseforge.com/minecraft/mc-mods/redstone-mod-by-poetic_death)").

I'll close this issue now since you've read it.

thanks for your mini mods btw - I'm tired of good mods that are bloated with items, food, multi-step receipes, etc that I do not want. I prefer to add 30 mods that do 30 things vs 30 mods that do 3000 things!!

**Comment by nerdywhiteguy** [comment]
A few other foods that should *definitely* be on the default blacklist: **Pufferfish and Chorus Fruit!** Pufferfish give you 60 seconds of Poison IV, 15 seconds of Nausea III, *and* 15 seconds of Hunger III. You *will* have half of a heart left after this. Chorus Fruit, meanwhile, *teleport you around*. Imagine exploring the End and you just suddenly teleport because you were hungry with a Chorus Fruit in your inventory. D-:

At an absolute bare minimum, it should default to `["minecraft:chorus_fruit", "minecraft:pufferfish", "minecraft:rotten_flesh", "minecraft:spider_eye", "minecraft:poisonous_potato"]` as those items all *do bad things to you* when eaten. A conscious effort should be required in order to eat one of these items.

Until #24 is implemented, I manually blacklisted all "raw" foods, and in my modpack I have both the Undergarden and Better End installed, so my blacklist is currently:
```TOML
food_blacklist = ["minecraft:chorus_fruit", "minecraft:pufferfish", "minecraft:rotten_flesh", "minecraft:spider_eye", "minecraft:poisonous_potato", "minecraft:potato", "minecraft:porkchop", "minecraft:cod", "minecraft:salmon", "minecraft:beef", "minecraft:chicken", "minecraft:rabbit", "minecraft:mutton", "undergarden:droopvine_item", "undergarden:raw_dweller_meat", "undergarden:raw_gwibling", "undergarden:raw_gloomper_leg", "undergarden:underbeans", "betterendforge:chorus_mushroom_raw", "betterendforge:end_fish_raw"]
```
Droopfruit aka `droopvine_item` from the Undergarden is another example of something that really shouldn't be eaten automatically as it gives you 30 seconds of glowing and provides minimal nutrition. I also have Mekanism installed, so I also added the Canteen to the whitelist (which works fabulously, I might add):
```TOML
food_whitelist = ["mekanism:canteen"]
```

**Comment by canitzp** [comment]
I have actually implemented it yesterday with the following entries:
`["minecraft:rotten_flesh", "minecraft:spider_eye", "minecraft:porkchop", "minecraft:beef", "minecraft:mutton", "minecraft:salmon", "minecraft:chicken", "minecraft:rabbit", "minecraft:potato", "minecraft:chorus_fruit", "minecraft:pufferfish", "minecraft:poisonous_potato"]`

I also added #24 but made it default disabled, due to it causing problems in big modpacks, where a lot of food, actually can be smelted further
