### ISSUE TITLE
[Crash] Crash while loadind world.

### ISSUE THREAD

**Issue by KrolMC** [canitzp/FeederHelmet#26]
Hello,
I'll finded crash while entering to the world with FeederHelmet mod.

Minecraft Version: 1.17.1
FeederHelmet Version: 1.12.0

Crash Log: [crash-2021-07-27_06.29.54-server.txt](https://github.com/canitzp/FeederHelmet/files/6882688/crash-2021-07-27_06.29.54-server.txt)
Latest Log: [latest.log](https://github.com/canitzp/FeederHelmet/files/6882692/latest.log)

**Comment by canitzp** [comment]
@KrolMC Can you please test this modified version for me and send me the log file? You have to unzip the file and use the .jar in it as mod. I can't upload .jar directly due to github restrictions.
Please let me know asap, so I can upload the fixed file to curseforge :).
[UnzipMe.zip](https://github.com/canitzp/FeederHelmet/files/6883511/UnzipMe.zip)

**Comment by KrolMC** [comment]
This version is working good, i don't have crash when I creating new world.

This is latest.log from my game: [latest.log](https://github.com/canitzp/FeederHelmet/files/6884186/latest.log)

**Comment by canitzp** [comment]
@KrolMC please try to craft a feeder helmet, I can't find any evidence in the log that the recipe registering has worked properly

**Comment by KrolMC** [comment]
I crafted a one, and game works, thanks!

**Comment by canitzp** [comment]
Okay thank you for your investigative help :+1:
