### ISSUE TITLE
[1.20.1] Description still lists crafting as method to apply, no recipe in JEI smithing tab. 

### ISSUE THREAD

**Issue by Xetaxheb** [canitzp/FeederHelmet#35]
Tried multiple forge versions with 47.0.1. It's just not working at all. No other mods besides AFH.

**Comment by Xetaxheb** [comment]
This is because the description still lists "crafting table" as the method... and JEI doesn't show smithing table as a valid applique.

**Comment by canitzp** [comment]
Sorry for the late apply.
Indeed you're right, JEI does not show the recipes, besides me trying to implement it. I think this is due to me not using a empty template item in the recipe.
The wrong description is an oversight on my side and I'll fix it soon, but this alone is not really worth a new release.

**Comment by canitzp** [comment]
The issue is resolved now. I implemented custom JEI integration and changed the description. Included in version 47.1.0 which is already released.
