### ISSUE TITLE
construct armory support

### ISSUE THREAD

**Issue by ilhamfu** [canitzp/FeederHelmet#4]
i have been playing with this mod quite a while, but then i decided to use construct armory armor (armor addon for tin con) . can you add compatibility to helmet from this mod

**Comment by canitzp** [comment]
@ilhamsitok This should already be possible by default, since the Helmets from ConstrucsArmory are extending ItemArmor

**Comment by TheDeviantCrafter** [comment]
I can confirm that it doesn't work on Construct's Armory helmets.

**Comment by canitzp** [comment]
Ok, when I have some time than I take a look into it, but don't expect it soon

**Comment by canitzp** [comment]
@TheDeviantCrafter @ilhamsitok I now took a look into the situation and installed autofeederhelmet and construct armory in a normal environment. Without a problem can I craft a feeder module with any of the helmets from construct armory. The only thing I noticed is that the JEI recipe view is a bit broken, since it doesn't show the correct helmet as output, but the recipe itself works just fine: 
![pic](http://puu.sh/Bf8jU/2b39ee58c7.jpg)

**Comment by canitzp** [comment]
Please present pictures or videos, if it doesn't work for you @TheDeviantCrafter @ilhamsitok and reopen the issue if so.

**Comment by freakone20** [comment]
work for me
